// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjkUnj8wlDx4A--vzTnsKTzhjpJqlfz4I',
    appId: '1:396426046330:web:95937e577415791c9a44c3',
    messagingSenderId: '396426046330',
    projectId: 'signin-41c36',
    authDomain: 'signin-41c36.firebaseapp.com',
    storageBucket: 'signin-41c36.appspot.com',
    measurementId: 'G-HQLC8RNBZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqd_QbxAb1SeALET0HLAHpy3CxU-AcOSc',
    appId: '1:396426046330:android:6987bd5ad5d879b39a44c3',
    messagingSenderId: '396426046330',
    projectId: 'signin-41c36',
    storageBucket: 'signin-41c36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBepReqSeRqFXxuF9cmYWliDqqyiCUAuNo',
    appId: '1:396426046330:ios:ef8a8021ac898c409a44c3',
    messagingSenderId: '396426046330',
    projectId: 'signin-41c36',
    storageBucket: 'signin-41c36.appspot.com',
    iosClientId: '396426046330-km38g5aih6oeqlel1d14ngffdoa9euaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBepReqSeRqFXxuF9cmYWliDqqyiCUAuNo',
    appId: '1:396426046330:ios:ef8a8021ac898c409a44c3',
    messagingSenderId: '396426046330',
    projectId: 'signin-41c36',
    storageBucket: 'signin-41c36.appspot.com',
    iosClientId: '396426046330-km38g5aih6oeqlel1d14ngffdoa9euaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSignin',
  );
}
